### PR TITLE
added three new metrics on different levels of active editors

### PR DESCRIPTION
**Pull request by LSDRH**

### CODE REVIEW

**Comment by Akronix** [comment]
Could you provide a bit of background, past discussions, link to issues, anything...please?

**Comment by LSDRH** [comment]
The three new metrics get the number of users that have contributed to the wiki in more than 4, 24 and 99 editions each month.
To do so, four functions have been created:

1. **users_active_more_than_x_editions(data, index, x)**: helper function which creates a new column in the dataframe, which contains the number of editions that each user has done on each month: 'pages_edited'. Then, it creates a new series which contains, per month, the users that have done more than X editions. At last, it counts the number of users that have done more than X editions on each month, and returns a pandas series with all the months of the wiki, and the number of users contributing in more than X editions during that month.
2. **users_active_more_than_4_editions(data, index)**: it calls users_active_more_than_x_editions with X = 4, as we want to get the users that have contributed to the wiki in more than 4 editions.
3. **users_active_more_than_24_editions(data, index)**: it calls users_active_more_than_x_editions with X = 24, as we want to get the users that have contributed to the wiki in more than 24 editions.
4. **users_active_more_than_99_editions(data, index)**: it calls users_active_more_than_x_editions with X = 99, as we want to get the users that have contributed to the wiki in more than 99 editions.

**Comment by Akronix** [comment]
Metric names are too long. They shouldn't be longer than one line, otherwise the info icons get misplaced. See:
image

Please fix this. Otherwise , LGTM.

**Review by Akronix — CHANGES_REQUESTED** [review]
Please, make metric names shorter to fit in one line.

**Pull request merged**
