### PR TITLE
removes fixed dependencies

### PR DESCRIPTION
**Pull request by FRYoussef**
I was unable to install the python dependencies. 

Some of the fixed dependencies has been deprecated, and an error comes up when you try installing them.

I've removed the versions, excepting the visual dependencies (dash, plotly) 'cause they can crash the app.  Take into account that if you used some deprecated functions or utilities, installing new versions would break the app. I've tested some features from WCh mono, networks, compare and work fine; however, please, take a second glance.

Everything was tested under Ubuntu20 and Python3.8.

### CODE REVIEW

**Comment by Akronix** [comment]
I really don't like the idea of latest cutting edge versions for a mature project like this. It can break everything up very easily. The most I can accept is something like compatible release (`~=`) or equal to major release (`== 1.*`)

Anyways, I just tried to reinstall the project and I didn't get any errors or warning when installing those packages with pip. Could you share specifically what error message are you getting?

**Comment by Akronix** [comment]
It might be related with you're using python 3.8 whereas I'm using 3.6.

**Comment by Akronix** [comment]
Would it be too hard for you to downgrade to python 3.6 for this project? You can use [pyenv](https://github.com/pyenv/pyenv) to easily switch between versions.

**Comment by FRYoussef** [comment]
I've checked python 3.6 and works fine.

The error is related to CPython and its dependency on some packages like scipy, pandas, igraph, etc. Each version of python has an associated CPython compilation, specific versions of dependencies don't exist in the following versions of python.

I haven't removed versions of dash, which potentially break the app. However, if you are concerned, then close this PR, and update the readme with the corrections of python versions.

**Comment by Akronix** [comment]
I'll close this then

**Pull request closed without merging**
