### PR TITLE
Added the two complementary metrics for active users close #38

### LINKED ISSUE #38: [New metric] active users metrics
To do the missing two complementary metrics for active users:
- [ ] Active registered users
- [ ] Active anonymous users

### PR DESCRIPTION
**Pull request by laudf**

### CODE REVIEW

**Comment by Akronix** [comment]
2 things:
- If you are reusing code. Don't copy the code, but call to the already existing function that does the code. This is a very basic principle in programming
- Mind the whitespaces: 2 new lines between function definitions, spaces around the operators (`,`, `=`, etc.). We are trying to follow, at least up to a minimum point, pep8 code styling guide: https://www.python.org/dev/peps/pep-0008/

**Review by Akronix — CHANGES_REQUESTED** [review]
2 things:
- If you are reusing code. Don't copy the code, but call to the already existing function that does the code. This is a very basic principle in programming
- Mind the whitespaces: 2 new lines between function definitions, spaces around the operators (`,`, `=`, etc.). We are trying to follow, at least up to a minimum point, pep8 code styling guide: https://www.python.org/dev/peps/pep-0008/

**Comment by laudf** [comment]
the whitespaces are already added

**Comment by Akronix** [comment]
Two things:
1. Please, don't use tabs in **any part of the code**. I see two tabs characters in your code.
2. You are still reusing code of  the`users_active()` function and don't making the call to that function.

**Pull request merged**
