### PR TITLE
Change colors in the bar chart (monowiki)

### PR DESCRIPTION
**Pull request by laudf**

### CODE REVIEW

**Comment by Akronix** [comment]
@FRYoussef do you think we could use one of the libraries we already have for color gradients, like https://pypi.org/project/colormap/ or https://pypi.org/project/colorama/ instead of adding a new dependency?
@laudf please take a look at those first.

**Comment by Akronix** [comment]
Also, can you please attach a screenshot of how the new colors look like?

**Comment by FRYoussef** [comment]
> 
> 
> @FRYoussef do you think we could use one of the libraries we already have for color gradients, like https://pypi.org/project/colormap/ or https://pypi.org/project/colorama/ instead of adding a new dependency?
> @laudf please take a look at those first.

Yep, I think so. You could use igraph as well, igraph provides a tiny API to deal with colours. Check this [https://igraph.org/python/doc/python-igraph.pdf](url) (**page 321**)

**Comment by Akronix** [comment]
> > @FRYoussef do you think we could use one of the libraries we already have for color gradients, like https://pypi.org/project/colormap/ or https://pypi.org/project/colorama/ instead of adding a new dependency?
> > @laudf please take a look at those first.
> 
> Yep, I think so. You could use igraph as well, igraph provides a tiny API to deal with colours. Check this [https://igraph.org/python/doc/python-igraph.pdf](url) (**page 321**)

Hum, I'd avoid to use igraph just for colours if we have other libraries available, so that we can run monowiki without igraph plus it's easier to move to another network backend (in case we ever want to).

**Comment by laudf** [comment]
I close this PR because I have opened a new one with the modifications.

**Pull request closed without merging**
